exclude: |
  (?x)
  ^setup/
  | /static/description/index\.html$
  | ^docs/corpus/
  | \.svg$
  | /tests/([^/]+/)?cassettes/
  | ^\.copier-answers\.yml$
  | ^\.github/
  | ^README\.md$
  | ^docs/_templates/.*\.html$
  | readme/.*\.(rst|md)$
  | /build/
  | /dist/
  | /dev/
  | /notebooks/
  | (LICENSE.*|COPYING.*)
default_language_version:
  python: python3
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --exit-non-zero-on-fix --force-exclude
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: ruff format --force-exclude
        language: system
        types_or: [python, pyi]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier (with plugin-xml)
        additional_dependencies:
          - "prettier@2.7.1"
          - "@prettier/plugin-xml@2.2.0"
        args:
          - --plugin=@prettier/plugin-xml
        files: \.(css|htm|html|js|json|jsx|less|md|scss|toml|ts|xml|yaml|yml)$
